sudo: false
language: node_js
notifications:
  email: false
node_js:
  - v8
install:
  - cd backend && npm install && cd ..
before_script:
  - yarn start-dev-apollo &
script:
  - cd backend && yarn test-travis --coverage
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)